apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrinder/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: stephengrinder/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: stephengrinder/multi-workder
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectel:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/server-cluster-ip-service.yml
      - k8s/client-cluster-ip-service.yml